baseurl = "http://speps.fr/"
languageCode = "en-us"
title = "speps.fr - RÃ©mi Gillig"
theme = "speps"
pygmentsUseClasses = true

[markup]
	[markup.highlight]
		lineNos = true

[taxonomies]
tag = "tags"